namespace Hosts_Pro_V6
{
	// Token: 0x02000019 RID: 25
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class V1 : global::System.Windows.Forms.Form
	{
		// Token: 0x06000159 RID: 345 RVA: 0x00009FC8 File Offset: 0x000081C8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600015A RID: 346 RVA: 0x0000A018 File Offset: 0x00008218
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Hosts_Pro_V6.V1));
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.Timer2 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer3 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer4 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer5 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer6 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer7 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer8 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer9 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer10 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer11 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer12 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer13 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer14 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer15 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer16 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer17 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer18 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer19 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer20 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer21 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer22 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer23 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer24 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer25 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer26 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer27 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer28 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer29 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer30 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer31 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer32 = new global::System.Windows.Forms.Timer(this.components);
			this.ToolStripStatusLabel1 = new global::System.Windows.Forms.ToolStripStatusLabel();
			this.ReactorTheme1 = new global::Hosts_Pro_V6.ReactorTheme();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.PictureBox8 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox7 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox6 = new global::System.Windows.Forms.PictureBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.ProgressBar1 = new global::System.Windows.Forms.ProgressBar();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.ReactorTabControl1 = new global::Hosts_Pro_V6.ReactorTabControl();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.PictureBox4 = new global::System.Windows.Forms.PictureBox();
			this.RadioButton4 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton3 = new global::System.Windows.Forms.RadioButton();
			this.CheckBox3 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.PictureBox5 = new global::System.Windows.Forms.PictureBox();
			this.ReactorButton1 = new global::Hosts_Pro_V6.ReactorButton();
			this.ReactorButton2 = new global::Hosts_Pro_V6.ReactorButton();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.RadioButton1 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton2 = new global::System.Windows.Forms.RadioButton();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Dlls = new global::System.Windows.Forms.ListBox();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.ReactorTheme1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox8).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox7).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox6).BeginInit();
			this.ReactorTabControl1.SuspendLayout();
			this.TabPage2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			this.TabPage3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).BeginInit();
			this.TabPage4.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.TabPage1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).BeginInit();
			base.SuspendLayout();
			this.OpenFileDialog1.ReadOnlyChecked = true;
			this.OpenFileDialog1.RestoreDirectory = true;
			this.OpenFileDialog1.ShowReadOnly = true;
			this.OpenFileDialog1.Title = "V6";
			this.ToolStripStatusLabel1.Name = "ToolStripStatusLabel1";
			this.ToolStripStatusLabel1.Size = new global::System.Drawing.Size(111, 17);
			this.ToolStripStatusLabel1.Text = "ToolStripStatusLabel1";
			this.ReactorTheme1.BackColor = global::System.Drawing.Color.Black;
			this.ReactorTheme1.Controls.Add(this.Button8);
			this.ReactorTheme1.Controls.Add(this.PictureBox8);
			this.ReactorTheme1.Controls.Add(this.PictureBox7);
			this.ReactorTheme1.Controls.Add(this.PictureBox6);
			this.ReactorTheme1.Controls.Add(this.Label7);
			this.ReactorTheme1.Controls.Add(this.Label4);
			this.ReactorTheme1.Controls.Add(this.Label5);
			this.ReactorTheme1.Controls.Add(this.ProgressBar1);
			this.ReactorTheme1.Controls.Add(this.TextBox1);
			this.ReactorTheme1.Controls.Add(this.ReactorTabControl1);
			this.ReactorTheme1.Controls.Add(this.Label1);
			this.ReactorTheme1.Controls.Add(this.RadioButton1);
			this.ReactorTheme1.Controls.Add(this.RadioButton2);
			this.ReactorTheme1.Controls.Add(this.CheckBox1);
			this.ReactorTheme1.Controls.Add(this.Label3);
			this.ReactorTheme1.Controls.Add(this.Dlls);
			this.ReactorTheme1.Controls.Add(this.Button4);
			this.ReactorTheme1.Controls.Add(this.Label2);
			this.ReactorTheme1.Controls.Add(this.Button3);
			this.ReactorTheme1.Controls.Add(this.Button2);
			this.ReactorTheme1.Controls.Add(this.Button1);
			this.ReactorTheme1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.ReactorTheme1.Font = new global::System.Drawing.Font("Verdana", 6.75f);
			this.ReactorTheme1.ForeColor = global::System.Drawing.Color.Red;
			this.ReactorTheme1.Location = new global::System.Drawing.Point(0, 0);
			this.ReactorTheme1.MaximumSize = new global::System.Drawing.Size(368, 458);
			this.ReactorTheme1.MinimumSize = new global::System.Drawing.Size(368, 458);
			this.ReactorTheme1.Name = "ReactorTheme1";
			this.ReactorTheme1.Size = new global::System.Drawing.Size(368, 458);
			this.ReactorTheme1.TabIndex = 0;
			this.ReactorTheme1.Text = "TH3KEN InjectoR V5";
			this.Button8.BackColor = global::System.Drawing.Color.Black;
			this.Button8.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.Button8.ForeColor = global::System.Drawing.Color.Lime;
			this.Button8.Location = new global::System.Drawing.Point(12, 297);
			this.Button8.Name = "Button8";
			this.Button8.Size = new global::System.Drawing.Size(155, 36);
			this.Button8.TabIndex = 41;
			this.Button8.Text = "Görev Yöneticisi Aç";
			this.Button8.UseVisualStyleBackColor = false;
			this.PictureBox8.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox8.Location = new global::System.Drawing.Point(273, 151);
			this.PictureBox8.Name = "PictureBox8";
			this.PictureBox8.Size = new global::System.Drawing.Size(56, 52);
			this.PictureBox8.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox8.TabIndex = 30;
			this.PictureBox8.TabStop = false;
			this.PictureBox8.Visible = false;
			this.PictureBox7.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox7.Image = global::Hosts_Pro_V6.My.Resources.Resources._256_256_05409bbfe3da6e971e94af5725956810;
			this.PictureBox7.Location = new global::System.Drawing.Point(271, 151);
			this.PictureBox7.Name = "PictureBox7";
			this.PictureBox7.Size = new global::System.Drawing.Size(56, 52);
			this.PictureBox7.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox7.TabIndex = 29;
			this.PictureBox7.TabStop = false;
			this.PictureBox7.Visible = false;
			this.PictureBox6.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox6.Image = global::Hosts_Pro_V6.My.Resources.Resources.loading;
			this.PictureBox6.Location = new global::System.Drawing.Point(271, 151);
			this.PictureBox6.Name = "PictureBox6";
			this.PictureBox6.Size = new global::System.Drawing.Size(56, 52);
			this.PictureBox6.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox6.TabIndex = 28;
			this.PictureBox6.TabStop = false;
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.ForeColor = global::System.Drawing.Color.Lime;
			this.Label7.Location = new global::System.Drawing.Point(84, 201);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(10, 12);
			this.Label7.TabIndex = 27;
			this.Label7.Text = "-";
			this.Label7.Visible = false;
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Location = new global::System.Drawing.Point(11, 201);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(10, 12);
			this.Label4.TabIndex = 26;
			this.Label4.Text = "-";
			this.Label4.Visible = false;
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Verdana", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 162);
			this.Label5.ForeColor = global::System.Drawing.Color.Lime;
			this.Label5.Location = new global::System.Drawing.Point(148, 152);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(12, 14);
			this.Label5.TabIndex = 25;
			this.Label5.Text = "-";
			this.ProgressBar1.Location = new global::System.Drawing.Point(255, 342);
			this.ProgressBar1.MaximumSize = new global::System.Drawing.Size(257, 287);
			this.ProgressBar1.Name = "ProgressBar1";
			this.ProgressBar1.Size = new global::System.Drawing.Size(105, 13);
			this.ProgressBar1.Style = global::System.Windows.Forms.ProgressBarStyle.Continuous;
			this.ProgressBar1.TabIndex = 24;
			this.TextBox1.BackColor = global::System.Drawing.Color.Black;
			this.TextBox1.Cursor = global::System.Windows.Forms.Cursors.PanWest;
			this.TextBox1.Font = new global::System.Drawing.Font("Verdana", 7.1f);
			this.TextBox1.ForeColor = global::System.Drawing.Color.Lime;
			this.TextBox1.Location = new global::System.Drawing.Point(73, 33);
			this.TextBox1.MaximumSize = new global::System.Drawing.Size(256, 22);
			this.TextBox1.MaxLength = 21;
			this.TextBox1.MinimumSize = new global::System.Drawing.Size(256, 22);
			this.TextBox1.Multiline = true;
			this.TextBox1.Name = "TextBox1";
			this.TextBox1.ReadOnly = true;
			this.TextBox1.Size = new global::System.Drawing.Size(256, 22);
			this.TextBox1.TabIndex = 3;
			this.TextBox1.Text = "DLL , Seçtikten Sorna Açılacaktır !";
			this.ReactorTabControl1.Controls.Add(this.TabPage2);
			this.ReactorTabControl1.Controls.Add(this.TabPage3);
			this.ReactorTabControl1.Controls.Add(this.TabPage4);
			this.ReactorTabControl1.Controls.Add(this.TabPage1);
			this.ReactorTabControl1.Location = new global::System.Drawing.Point(8, 361);
			this.ReactorTabControl1.Name = "ReactorTabControl1";
			this.ReactorTabControl1.SelectedIndex = 0;
			this.ReactorTabControl1.Size = new global::System.Drawing.Size(357, 90);
			this.ReactorTabControl1.TabBorderColor = global::System.Drawing.Color.Maroon;
			this.ReactorTabControl1.TabIndex = 22;
			this.ReactorTabControl1.TabTextColor = global::System.Drawing.Color.White;
			this.TabPage2.BackColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.TabPage2.Controls.Add(this.Button5);
			this.TabPage2.Controls.Add(this.Label6);
			this.TabPage2.Controls.Add(this.PictureBox3);
			this.TabPage2.Location = new global::System.Drawing.Point(4, 25);
			this.TabPage2.Name = "TabPage2";
			this.TabPage2.Size = new global::System.Drawing.Size(349, 61);
			this.TabPage2.TabIndex = 4;
			this.TabPage2.Text = "Clear Temp";
			this.Button5.BackColor = global::System.Drawing.Color.Black;
			this.Button5.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button5.Font = new global::System.Drawing.Font("Verdana", 8.75f);
			this.Button5.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			this.Button5.Location = new global::System.Drawing.Point(182, 13);
			this.Button5.Name = "Button5";
			this.Button5.Size = new global::System.Drawing.Size(164, 33);
			this.Button5.TabIndex = 25;
			this.Button5.Text = "Clear LOG";
			this.Button5.UseVisualStyleBackColor = false;
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 162);
			this.Label6.ForeColor = global::System.Drawing.Color.Yellow;
			this.Label6.Location = new global::System.Drawing.Point(3, 21);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(173, 16);
			this.Label6.TabIndex = 26;
			this.Label6.Text = "Gereksiz Dosyaları Siler >";
			this.PictureBox3.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.PictureBox3.Location = new global::System.Drawing.Point(0, 0);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(349, 61);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox3.TabIndex = 0;
			this.PictureBox3.TabStop = false;
			this.TabPage3.BackColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.TabPage3.Controls.Add(this.PictureBox4);
			this.TabPage3.Controls.Add(this.RadioButton4);
			this.TabPage3.Controls.Add(this.RadioButton3);
			this.TabPage3.Controls.Add(this.CheckBox3);
			this.TabPage3.Controls.Add(this.CheckBox2);
			this.TabPage3.Location = new global::System.Drawing.Point(4, 25);
			this.TabPage3.Name = "TabPage3";
			this.TabPage3.Size = new global::System.Drawing.Size(349, 61);
			this.TabPage3.TabIndex = 3;
			this.TabPage3.Text = "Settings";
			this.PictureBox4.Image = global::Hosts_Pro_V6.My.Resources.Resources.ayar;
			this.PictureBox4.Location = new global::System.Drawing.Point(139, 8);
			this.PictureBox4.Name = "PictureBox4";
			this.PictureBox4.Size = new global::System.Drawing.Size(53, 48);
			this.PictureBox4.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox4.TabIndex = 28;
			this.PictureBox4.TabStop = false;
			this.RadioButton4.AutoSize = true;
			this.RadioButton4.BackColor = global::System.Drawing.Color.Transparent;
			this.RadioButton4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.RadioButton4.Font = new global::System.Drawing.Font("Montserrat", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RadioButton4.ForeColor = global::System.Drawing.Color.Lime;
			this.RadioButton4.Location = new global::System.Drawing.Point(4, 36);
			this.RadioButton4.Name = "RadioButton4";
			this.RadioButton4.Size = new global::System.Drawing.Size(90, 23);
			this.RadioButton4.TabIndex = 26;
			this.RadioButton4.Text = "RGB ON";
			this.RadioButton4.UseVisualStyleBackColor = false;
			this.RadioButton3.AutoSize = true;
			this.RadioButton3.BackColor = global::System.Drawing.Color.Transparent;
			this.RadioButton3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.RadioButton3.Font = new global::System.Drawing.Font("Montserrat", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RadioButton3.ForeColor = global::System.Drawing.Color.Red;
			this.RadioButton3.Location = new global::System.Drawing.Point(4, 4);
			this.RadioButton3.Name = "RadioButton3";
			this.RadioButton3.Size = new global::System.Drawing.Size(95, 23);
			this.RadioButton3.TabIndex = 25;
			this.RadioButton3.Text = "RGB OFF";
			this.RadioButton3.UseVisualStyleBackColor = false;
			this.CheckBox3.AutoSize = true;
			this.CheckBox3.BackColor = global::System.Drawing.Color.Transparent;
			this.CheckBox3.ForeColor = global::System.Drawing.Color.Lime;
			this.CheckBox3.Location = new global::System.Drawing.Point(236, 11);
			this.CheckBox3.Name = "CheckBox3";
			this.CheckBox3.Size = new global::System.Drawing.Size(109, 16);
			this.CheckBox3.TabIndex = 27;
			this.CheckBox3.Text = "SECURİTY MOD";
			this.CheckBox3.UseVisualStyleBackColor = false;
			this.CheckBox2.AutoSize = true;
			this.CheckBox2.BackColor = global::System.Drawing.Color.Transparent;
			this.CheckBox2.ForeColor = global::System.Drawing.Color.Lime;
			this.CheckBox2.Location = new global::System.Drawing.Point(269, 41);
			this.CheckBox2.Name = "CheckBox2";
			this.CheckBox2.Size = new global::System.Drawing.Size(77, 16);
			this.CheckBox2.TabIndex = 26;
			this.CheckBox2.Text = "VAC MOD";
			this.CheckBox2.UseVisualStyleBackColor = false;
			this.TabPage4.BackColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.TabPage4.Controls.Add(this.PictureBox2);
			this.TabPage4.Controls.Add(this.PictureBox1);
			this.TabPage4.Controls.Add(this.Button6);
			this.TabPage4.Location = new global::System.Drawing.Point(4, 25);
			this.TabPage4.Name = "TabPage4";
			this.TabPage4.Size = new global::System.Drawing.Size(349, 61);
			this.TabPage4.TabIndex = 5;
			this.TabPage4.Text = "LOG";
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(21, 8);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(55, 50);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox2.TabIndex = 29;
			this.PictureBox2.TabStop = false;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(261, 8);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(54, 53);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 28;
			this.PictureBox1.TabStop = false;
			this.Button6.BackColor = global::System.Drawing.Color.Black;
			this.Button6.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button6.Font = new global::System.Drawing.Font("Verdana", 8.75f);
			this.Button6.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			this.Button6.Location = new global::System.Drawing.Point(92, 14);
			this.Button6.Name = "Button6";
			this.Button6.Size = new global::System.Drawing.Size(154, 39);
			this.Button6.TabIndex = 25;
			this.Button6.Text = "LOG Görüntüle";
			this.Button6.UseVisualStyleBackColor = false;
			this.TabPage1.BackColor = global::System.Drawing.Color.FromArgb(32, 32, 32);
			this.TabPage1.Controls.Add(this.PictureBox5);
			this.TabPage1.Controls.Add(this.ReactorButton1);
			this.TabPage1.Controls.Add(this.ReactorButton2);
			this.TabPage1.Cursor = global::System.Windows.Forms.Cursors.PanWest;
			this.TabPage1.Location = new global::System.Drawing.Point(4, 25);
			this.TabPage1.Name = "TabPage1";
			this.TabPage1.Size = new global::System.Drawing.Size(349, 61);
			this.TabPage1.TabIndex = 2;
			this.TabPage1.Text = "Nasıl Çalışır ? ";
			this.PictureBox5.Image = global::Hosts_Pro_V6.My.Resources.Resources.de2dc181345311691d49ad48250ae06f;
			this.PictureBox5.Location = new global::System.Drawing.Point(226, 8);
			this.PictureBox5.Name = "PictureBox5";
			this.PictureBox5.Size = new global::System.Drawing.Size(123, 50);
			this.PictureBox5.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox5.TabIndex = 2;
			this.PictureBox5.TabStop = false;
			this.ReactorButton1.BackColor = global::System.Drawing.Color.Red;
			this.ReactorButton1.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 162);
			this.ReactorButton1.ForeColor = global::System.Drawing.Color.Red;
			this.ReactorButton1.Location = new global::System.Drawing.Point(4, 3);
			this.ReactorButton1.Name = "ReactorButton1";
			this.ReactorButton1.Size = new global::System.Drawing.Size(103, 34);
			this.ReactorButton1.TabIndex = 0;
			this.ReactorButton1.Text = "Bilgi Al";
			this.ReactorButton2.BackColor = global::System.Drawing.Color.Red;
			this.ReactorButton2.Font = new global::System.Drawing.Font("Verdana", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 162);
			this.ReactorButton2.ForeColor = global::System.Drawing.Color.Purple;
			this.ReactorButton2.Location = new global::System.Drawing.Point(114, 3);
			this.ReactorButton2.Name = "ReactorButton2";
			this.ReactorButton2.Size = new global::System.Drawing.Size(106, 34);
			this.ReactorButton2.TabIndex = 1;
			this.ReactorButton2.Text = "Nasıl Çalışır ?";
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.739999f);
			this.Label1.ForeColor = global::System.Drawing.Color.Yellow;
			this.Label1.Location = new global::System.Drawing.Point(11, 342);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(31, 16);
			this.Label1.TabIndex = 5;
			this.Label1.Text = ">...<";
			this.Label1.Visible = false;
			this.RadioButton1.AutoSize = true;
			this.RadioButton1.BackColor = global::System.Drawing.Color.Transparent;
			this.RadioButton1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.RadioButton1.Font = new global::System.Drawing.Font("Kristen ITC", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RadioButton1.ForeColor = global::System.Drawing.Color.Cyan;
			this.RadioButton1.Location = new global::System.Drawing.Point(10, 241);
			this.RadioButton1.MaximumSize = new global::System.Drawing.Size(167, 27);
			this.RadioButton1.MinimumSize = new global::System.Drawing.Size(167, 27);
			this.RadioButton1.Name = "RadioButton1";
			this.RadioButton1.Size = new global::System.Drawing.Size(167, 27);
			this.RadioButton1.TabIndex = 21;
			this.RadioButton1.Text = "Automatic Inject";
			this.RadioButton1.UseVisualStyleBackColor = false;
			this.RadioButton2.AutoSize = true;
			this.RadioButton2.BackColor = global::System.Drawing.Color.Transparent;
			this.RadioButton2.Checked = true;
			this.RadioButton2.Font = new global::System.Drawing.Font("Kristen ITC", 11.25f);
			this.RadioButton2.ForeColor = global::System.Drawing.Color.Yellow;
			this.RadioButton2.Location = new global::System.Drawing.Point(234, 241);
			this.RadioButton2.MaximumSize = new global::System.Drawing.Size(140, 27);
			this.RadioButton2.MinimumSize = new global::System.Drawing.Size(140, 27);
			this.RadioButton2.Name = "RadioButton2";
			this.RadioButton2.Size = new global::System.Drawing.Size(140, 27);
			this.RadioButton2.TabIndex = 17;
			this.RadioButton2.TabStop = true;
			this.RadioButton2.Text = "Manuel Inject";
			this.RadioButton2.UseVisualStyleBackColor = false;
			this.CheckBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.CheckBox1.Cursor = global::System.Windows.Forms.Cursors.Cross;
			this.CheckBox1.Font = new global::System.Drawing.Font("Microsoft Office Preview Font", 9.75f);
			this.CheckBox1.ForeColor = global::System.Drawing.Color.FromArgb(192, 64, 0);
			this.CheckBox1.Location = new global::System.Drawing.Point(225, 316);
			this.CheckBox1.Name = "CheckBox1";
			this.CheckBox1.Size = new global::System.Drawing.Size(148, 21);
			this.CheckBox1.TabIndex = 1;
			this.CheckBox1.Text = "Inject Edince Kapat";
			this.CheckBox1.UseVisualStyleBackColor = false;
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label3.Font = new global::System.Drawing.Font("Arial Rounded MT Bold", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.Red;
			this.Label3.Location = new global::System.Drawing.Point(322, 37);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(46, 17);
			this.Label3.TabIndex = 18;
			this.Label3.Text = " .EXE";
			this.Dlls.BackColor = global::System.Drawing.Color.Black;
			this.Dlls.DisplayMember = "3";
			this.Dlls.Enabled = false;
			this.Dlls.Font = new global::System.Drawing.Font("Verdana", 7.3f);
			this.Dlls.ForeColor = global::System.Drawing.Color.Red;
			this.Dlls.ItemHeight = 12;
			this.Dlls.Location = new global::System.Drawing.Point(145, 60);
			this.Dlls.Name = "Dlls";
			this.Dlls.Size = new global::System.Drawing.Size(182, 88);
			this.Dlls.TabIndex = 14;
			this.Button4.BackColor = global::System.Drawing.SystemColors.WindowText;
			this.Button4.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button4.Font = new global::System.Drawing.Font("Nexa Light", 10.25f);
			this.Button4.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			this.Button4.Location = new global::System.Drawing.Point(8, 95);
			this.Button4.Name = "Button4";
			this.Button4.Size = new global::System.Drawing.Size(128, 31);
			this.Button4.TabIndex = 12;
			this.Button4.Text = "Seçtigini Sil";
			this.Button4.UseVisualStyleBackColor = false;
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Cooper Black", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.White;
			this.Label2.Location = new global::System.Drawing.Point(6, 37);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(70, 14);
			this.Label2.TabIndex = 6;
			this.Label2.Text = "PROCESS:";
			this.Button3.BackColor = global::System.Drawing.Color.Black;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.Button3.ForeColor = global::System.Drawing.Color.White;
			this.Button3.Location = new global::System.Drawing.Point(8, 161);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(128, 36);
			this.Button3.TabIndex = 4;
			this.Button3.Text = "Inject Et";
			this.Button3.UseVisualStyleBackColor = false;
			this.Button2.BackColor = global::System.Drawing.Color.Black;
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button2.Font = new global::System.Drawing.Font("Nexa Light", 10.25f);
			this.Button2.ForeColor = global::System.Drawing.Color.Yellow;
			this.Button2.Location = new global::System.Drawing.Point(8, 130);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(128, 25);
			this.Button2.TabIndex = 3;
			this.Button2.Text = "Listeyi Sil";
			this.Button2.UseVisualStyleBackColor = false;
			this.Button1.BackColor = global::System.Drawing.Color.Black;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 162);
			this.Button1.ForeColor = global::System.Drawing.Color.Cyan;
			this.Button1.Location = new global::System.Drawing.Point(8, 60);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(128, 31);
			this.Button1.TabIndex = 2;
			this.Button1.Text = "Seç";
			this.Button1.UseVisualStyleBackColor = false;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			base.ClientSize = new global::System.Drawing.Size(368, 458);
			base.Controls.Add(this.ReactorTheme1);
			this.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.ForeColor = global::System.Drawing.Color.Black;
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "V1";
			this.Text = "TH3KEN InjectoR V5";
			this.ReactorTheme1.ResumeLayout(false);
			this.ReactorTheme1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox8).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox7).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox6).EndInit();
			this.ReactorTabControl1.ResumeLayout(false);
			this.TabPage2.ResumeLayout(false);
			this.TabPage2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			this.TabPage3.ResumeLayout(false);
			this.TabPage3.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).EndInit();
			this.TabPage4.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.TabPage1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x0400005B RID: 91
		private global::System.ComponentModel.IContainer components;
	}
}
